### ISSUE TITLE
Crash upon search

### ISSUE THREAD

**Issue by bvvt** [Wojnstup/PipeCat#1]
Following error after searching

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/youtubesearchpython/handlers/requesthandler.py", line 35, in _makeRequest
    self.response = urlopen(request, timeout=self.timeout).read().decode('utf_8')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/czr/Downloads/PipeCat-main/main.py", line 29, in <module>
    search_results = search(action.split(" ", 1)[1])
  File "/Users/czr/Downloads/PipeCat-main/functions.py", line 22, in search
    results = VideosSearch(query=query, limit=max_results).result()["result"]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/youtubesearchpython/search.py", line 142, in __init__
    super().__init__(query, limit, language, region, SearchMode.videos, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/youtubesearchpython/internal/search.py", line 21, in __init__
    self._makeRequest()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/youtubesearchpython/handlers/requesthandler.py", line 37, in _makeRequest
    raise Exception('ERROR: Could not make request.')
Exception: ERROR: Could not make request.
```

Running 

macOS BigSur

**Comment by Wojnstup** [comment]
Could you post exactly what you typed in? I'm not sure if I'll be able to help you since I tested it only on Linux and I do not own a Mac. It uses a os.system command that executes commands in your shell, which is bash on Linux and I'm pretty sure the same applies to other Unix-like systems like Mac, but I can't confirm if the behaviour is the same. Plese verify if all of the libraries are installed. Also check if mpv is installed (it propably isn't the root od your issue, but remember that It's required).

**Comment by bvvt** [comment]
> Could you post exactly what you typed in? I'm not sure if I'll be able to help you since I tested it only on Linux and I do not own a Mac. It uses a os.system command that executes commands in your shell, which is bash on Linux and I'm pretty sure the same applies to other Unix-like systems like Mac, but I can't confirm if the behaviour is the same. Plese verify if all of the libraries are installed. Also check if mpv is installed (it propably isn't the root od your issue, but remember that It's required).

I have all dependencies installed and i also have mpv installed,  mpv runs with no problem

I run it like this 

`python3 main.py`

then to search I performed

`search audio house`

**Comment by Wojnstup** [comment]
I don't know why It's not worling, maybe a MacOS thing. Again, I don't really know, cause I don't own a Mac and made the library with Linux in mind. Sorry that I can't help you, but I'm still at high school and I don't really have time to figure this out. If it was a Linux issue that would be a different story, since I could maybe try to reproduce the issue. Maybe try executing invidual functions from the libraries I used to swe if It's an issue with the?
